### ISSUE TITLE
-v 的参数怎么设置的呢

### ISSUE THREAD

**Issue by k2y1982** [activeliang/wgcf-socks5-proxy#2]
root@Nas:~# docker run --rm -it \
>   --name wgcf \
>   --sysctl net.ipv6.conf.all.disable_ipv6=0 \
>   --privileged --cap-add net_admin \
>   -p 7889:1080 \
>   -e USER=myuser \
>   -e PASSWORD=mypassword \
>   -e PORT=1080 \
>   -e HOST=0.0.0.0 \
>   activeliang/wgcf-socks5-proxy -6
2023/11/07 12:37:32 Using config file: wgcf-account.toml
2023/11/07 12:37:38 =======================================
2023/11/07 12:37:38 Device name   : 09C27B
2023/11/07 12:37:38 Device model  : PC
2023/11/07 12:37:38 Device active : true
2023/11/07 12:37:38 Account type  : free
2023/11/07 12:37:38 Role          : child
2023/11/07 12:37:38 Premium data  : 0.00 B
2023/11/07 12:37:38 Quota         : 0.00 B
2023/11/07 12:37:38 =======================================
2023/11/07 12:37:38 Successfully created Cloudflare Warp account
2023/11/07 12:37:38 Using config file: wgcf-account.toml
2023/11/07 12:37:40 =======================================
2023/11/07 12:37:40 Device name   : 09C27B
2023/11/07 12:37:40 Device model  : PC
2023/11/07 12:37:40 Device active : true
2023/11/07 12:37:40 Account type  : free
2023/11/07 12:37:40 Role          : child
2023/11/07 12:37:40 Premium data  : 0.00 B
2023/11/07 12:37:40 Quota         : 0.00 B
2023/11/07 12:37:40 =======================================
2023/11/07 12:37:40 Successfully generated WireGuard profile: wgcf-profile.conf
eth0
172.17.0.7
modprobe: can't change directory to '/lib/modules': No such file or directory

clean up
wg-quick: `wgcf' is not a WireGuard interface
error down
clean up done

**Comment by activeliang** [comment]
docker run --rm -it \
     --name wgcf \
     --sysctl net.ipv6.conf.all.disable_ipv6=0 \
     --privileged --cap-add net_admin \
     -v /lib/modules:/lib/modules \
     -v $(pwd)/wgcf:/wgcf \
     -p 7889:1080 \
     activeliang/wgcf-socks5-proxy -6
